### ISSUE TITLE
LIMIT 10?

### ISSUE THREAD

**Issue by hlohaus** [tinect/TinectTinyPngOptimizer#1]
https://github.com/FriendsOfShopware/FroshTinyPngMediaOptimizer/blob/e3a259f8edcaf430c567b402967fe406426e160e/Components/TinyPngOptimizer.php#L104

**Comment by tinect** [comment]
Yes, it's defined intentionally.
Cause this will be fired for every image. If the first update will result ALL images to get optimized, this will take some time.

I agree, this isn't optimal, but a way to go. Definitely not `carved in stone` :-)

**Comment by shyim** [comment]
is fixed with the pr
